import type { Metadata } from "next";
import Link from "next/link";
import { ProductVisual } from "../product-visual";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = {
  title: { absolute: "Praha Cut — Agentic Video Editor | Praha Lab" },
  description: "Praha Cut is an agentic video editor that understands editing intent, plans edits, operates editing tools, and builds an editable timeline.",
  openGraph: { title: "Praha Cut — Agentic Video Editor | Praha Lab", description: "Turn editing intent into an editable timeline. Praha Cut is in development at Praha Lab.", url: "https://prahalab.com/cut", type: "website", images: [{ url: "/cut-social.svg", width: 1200, height: 630, alt: "Praha Cut editor concept" }] },
};

const software = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Praha Cut", applicationCategory: "MultimediaApplication", description: "An in-development agentic video editor that turns editing intent into an editable timeline.", url: "https://prahalab.com/cut", creator: { "@type": "Organization", name: "Praha Lab", url: "https://prahalab.com/" } };

const tools = ["inspect footage", "transcribe", "find moment", "trim", "split", "reorder", "crop", "reframe", "caption", "overlay", "adjust audio", "render", "review"];

export default function CutPage() {
  return <main className="cut-site" id="top"><link rel="canonical" href="https://prahalab.com/cut" /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(software) }} /><a className="cut-skip" href="#main-content">Skip to content</a><SiteHeader active="product" /><div id="main-content">
    <section className="product-hero cut-container"><p className="cut-eyebrow"><span className="status-light" /> PRAHA CUT / IN DEVELOPMENT</p><h1>Video editing,<br /><em>directed in words.</em></h1><div className="product-hero-bottom"><p>Praha Cut is an agentic video editor that turns your editing intent into an editable timeline. Give it footage, describe the result, review a draft, and keep directing the edit.</p><Link className="cut-button" href="/#early-access">Join early access <span aria-hidden="true">↗</span></Link></div></section>
    <section className="cut-container product-visual-block"><div className="visual-intro"><span>PRODUCT INTERFACE CONCEPT</span><span>FOOTAGE / AGENT / TIMELINE</span></div><ProductVisual /></section>
    <section className="cut-section cut-container product-story" id="how-it-works"><div className="section-heading"><p className="cut-eyebrow">01 / FROM FOOTAGE TO DRAFT</p><h2>The edit starts<br />with intent.</h2><p>Describe the story, pacing, focus, and output format. Praha Cut is being designed to inspect footage and transcripts, make an editing plan, apply editing operations, and render a draft you can revise.</p></div><div className="product-example"><span>EXAMPLE DIRECTION</span><blockquote>“Turn this 12-minute recording into a 60-second launch video. Remove dead space, keep the benchmark section, zoom into the terminal when the results appear, add captions, and create a vertical version for Shorts.”</blockquote><p>This illustrates the intended workflow. It is not a claim that every operation is publicly available today.</p></div></section>
    <section className="cut-section cut-container product-stages"><p className="cut-eyebrow">02 / AGENT WORKFLOW</p><div className="stage-grid">{[{ n: "01", title: "Understand", text: "Reason over user intent, transcript, and footage context to identify the moments that matter." }, { n: "02", title: "Plan", text: "Construct a sequence of edits and choose the media tools needed to execute it." }, { n: "03", title: "Operate", text: "Apply cuts, ordering, captions, reframing, and audio changes to an editable timeline." }, { n: "04", title: "Revise", text: "Keep the timeline state and respond to further direction without resetting the edit." }].map(step => <article key={step.n}><span>{step.n}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
    <section className="cut-section cut-container timeline-philosophy" id="timeline"><div><p className="cut-eyebrow">03 / CREATIVE CONTROL</p><h2>The timeline<br />isn&apos;t going away.</h2></div><div><p>Natural language handles high-level intent. The timeline preserves precision and control. Praha Cut is designed to let you say “don&apos;t cut between these two sentences” or “restore the explanation before the demo” and then inspect the changed edit.</p><div className="timeline-philosophy-strip"><span>INTENT</span><b>→</b><span>EDITABLE TIMELINE</span><b>→</b><span>YOUR FINAL CUT</span></div><strong>Describe the edit at the level humans think about it. Take control at the level editors need.</strong></div></section>
    <section className="cut-section cut-container product-architecture"><div className="section-heading"><p className="cut-eyebrow">04 / ARCHITECTURE</p><h2>Reasoning meets<br />an editing system.</h2><p>Praha Cut is being built with Claude as the reasoning and tool-use layer. Praha Lab builds the media processing, timeline representation, editing operations, state, execution, and rendering around it.</p></div><div className="architecture-grid"><div><span>INPUTS</span><strong>Footage<br />Transcript<br />User direction</strong></div><div><span>REASONING</span><strong>Claude</strong><p>Interpret intent, plan changes, select tools, support revision.</p></div><div><span>EXECUTION</span><strong>Praha Cut</strong><p>Media tools, non-destructive timeline state, draft rendering.</p></div></div></section>
    <section className="cut-section cut-container tool-section"><div className="section-heading"><p className="cut-eyebrow">05 / TOOL SYSTEM</p><h2>An agent that<br />does the work.</h2><p>These are representative operations in the intended editing system, not a published API specification.</p></div><div className="tool-cloud">{tools.map((tool, index) => <span key={tool}><small>{String(index + 1).padStart(2, "0")}</small>{tool}()</span>)}</div></section>
    <section className="cut-section cut-container product-use"><div className="section-heading"><p className="cut-eyebrow">06 / USE CASES</p><h2>From raw to<br />ready to review.</h2></div><div className="use-list"><div><span>01</span><h3>Creators</h3><p>Shape long recordings into focused short-form stories.</p></div><div><span>02</span><h3>Founders & marketers</h3><p>Cut product demos and launch videos around the strongest moment.</p></div><div><span>03</span><h3>Podcasters</h3><p>Find clips while retaining the argument that gives them meaning.</p></div><div><span>04</span><h3>Developer advocates</h3><p>Keep the key terminal, code, benchmark, and explanation in frame.</p></div></div></section>
    <section className="product-close"><div className="cut-container"><p className="cut-eyebrow">PRAHA CUT / EARLY ACCESS</p><h2>Make the edit<br /><em>you meant.</em></h2><p>In development at Praha Lab. Tell us what you make and how you edit.</p><Link className="cut-button" href="/#early-access">Request early access <span aria-hidden="true">↗</span></Link></div></section>
  </div><SiteFooter /></main>;
}
