import Link from "next/link";
import { EarlyAccessForm } from "./early-access-form";
import { ProductVisual } from "./product-visual";
import { SiteFooter, SiteHeader } from "./site-chrome";
import { organization, projects } from "./site-data";

export default function Home() {
  return <main className="cut-site" id="top">
    <link rel="canonical" href="https://prahalab.com/" />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organization) }} />
    <a className="cut-skip" href="#main-content">Skip to content</a>
    <SiteHeader />
    <div id="main-content">
      <section className="cut-hero cut-container" aria-labelledby="home-title"><div className="cut-hero-copy"><p className="cut-eyebrow"><span className="status-light" /> PRAHA CUT / IN DEVELOPMENT</p><h1 id="home-title">Tell it what <em>to cut.</em></h1><p className="cut-lead">Edit video by telling an agent what you want.</p><p className="cut-hero-body">Praha Cut is an agentic video editor that turns your intent into an editable timeline. Give it raw footage. Describe the story you want. It plans the edit, operates editing tools, renders a draft, and keeps refining it with you.</p><div className="cut-actions"><Link className="cut-button" href="#early-access">Join early access <span aria-hidden="true">↗</span></Link><Link className="cut-text-action" href="#how-it-works">See how it works <span aria-hidden="true">↓</span></Link></div></div><div className="cut-hero-aside"><span>PRODUCT / 001</span><p>Words direct the edit.<br />The timeline stays yours.</p><span>AGENTIC VIDEO EDITING</span></div></section>
      <section className="visual-section cut-container" aria-label="Praha Cut interface concept"><div className="visual-intro"><span>THE EDITOR / A WORKING IDEA</span><span>01 — INTENT BECOMES A TIMELINE</span></div><ProductVisual /><div className="visual-outro"><p>A real editing surface, shaped around the way people describe stories.</p><Link href="/cut">Explore Praha Cut <span aria-hidden="true">↗</span></Link></div></section>
      <section className="cut-section cut-container intent-section" id="how-it-works" aria-labelledby="intent-title"><div className="section-heading"><p className="cut-eyebrow">01 / THE WORKFLOW</p><h2 id="intent-title">From intent<br />to timeline.</h2><p>Praha Cut doesn&apos;t just generate an answer. It is being built to operate an editing system, with Claude as the reasoning and tool-use layer.</p></div><div className="intent-diagram"><div className="intent-quote"><span>YOUR DIRECTION</span><blockquote>“Cut this into a fast 30-second vertical clip. Start with the strongest claim, remove filler, caption everything, and keep the demo.”</blockquote></div><div className="intent-flow"><span>Claude <small>reasoning + editing plan</small></span><b>↓</b><span>Praha Cut tools <small>inspect · trim · reframe · caption</small></span><b>↓</b><span>Editable timeline <small>review · revise · render</small></span></div></div></section>
      <section className="cut-section cut-container process-section" aria-labelledby="process-title"><div className="section-heading"><p className="cut-eyebrow">02 / WHAT THE AGENT DOES</p><h2 id="process-title">A director for<br />the tedious parts.</h2><p>One instruction can become a deliberate sequence of changes. Each stage stays visible and reviewable.</p></div><div className="process-grid"><div className="raw-frame"><div className="frame-top"><span>RAW FOOTAGE</span><span>12:43</span></div><div className="raw-frame-lines"><i /><i /><i /><i /><i /></div><p>“Make a 60-second product launch.”</p></div><div className="process-steps">{["Understand footage", "Find key moments", "Plan narrative", "Cut the timeline", "Add captions", "Reframe", "Render draft"].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}<span aria-hidden="true">↘</span></div>)}</div><div className="result-frame"><div className="frame-top"><span>ILLUSTRATIVE RESULT</span><span>00:58</span></div><div className="result-frame-art"><span>THE STORY,<br /><em>IN FOCUS.</em></span><i>▶</i></div><p>Concept sequence; no generated video is represented here.</p></div></div></section>
      <section className="cut-section cut-container direction-section" aria-labelledby="direction-title"><div><p className="cut-eyebrow">03 / NON-DESTRUCTIVE BY DESIGN</p><h2 id="direction-title">An agent you<br />can <em>direct.</em></h2><p>Say “restore the explanation before the demo,” “make the first ten seconds faster,” or “keep the original audio here.” Praha Cut is designed to modify the existing edit instead of starting over.</p><Link className="cut-text-action" href="/cut#timeline">The timeline philosophy <span aria-hidden="true">↗</span></Link></div><div className="revision-panel"><div className="revision-label">REVISION 03 / ILLUSTRATIVE</div><div className="revision-message">“Restore the explanation before the demo.”</div><div className="revision-track"><span>OPENING</span><span className="revision-return">EXPLANATION <b>RESTORED</b></span><span>DEMO</span></div><div className="revision-note"><span>↳</span> Existing cuts stay editable. A new revision changes the timeline.</div></div></section>
      <section className="cut-section cut-container principles-section" aria-labelledby="principles-title"><div className="section-heading"><p className="cut-eyebrow">04 / WHY CLAUDE</p><h2 id="principles-title">Reasoning behind<br />the edit.</h2><p>Editing takes more than finding silence. It means deciding what matters, how ideas connect, and what can disappear without changing the story.</p></div><div className="principles-layout"><p>Praha Cut is being built with Claude to reason over editing intent and content, construct an editing plan, select tools, and guide revision. Praha Lab’s system handles media processing, timeline state, editing operations, execution, and rendering.</p><div className="architecture-mini"><span>FOOTAGE + TRANSCRIPT + INTENT</span><b>↓</b><strong>Claude <small>reasoning / plan / tool use</small></strong><b>↓</b><span>PRAHA CUT TOOLS → TIMELINE → RENDER</span></div></div></section>
      <section className="cut-section cut-container use-section" aria-labelledby="use-title"><div className="section-heading"><p className="cut-eyebrow">05 / BUILT FOR THE WORK</p><h2 id="use-title">Less searching.<br />More shaping.</h2></div><div className="use-list"><div><span>01</span><h3>Long → short</h3><p>Find a focused story inside a podcast or recording.</p></div><div><span>02</span><h3>Product demos</h3><p>Build concise demonstrations around the moments that matter.</p></div><div><span>03</span><h3>Social versions</h3><p>Plan shorter edits and alternate framing for different formats.</p></div><div><span>04</span><h3>Technical content</h3><p>Keep the code, terminal, benchmark, or diagram that carries the point.</p></div></div></section>
      <section className="early-section" id="early-access" aria-labelledby="early-title"><div className="cut-container early-inner"><div><p className="cut-eyebrow">EARLY ACCESS / PRAHA CUT</p><h2 id="early-title">Direct your<br /><em>next edit.</em></h2><p>Praha Cut is in development. Tell us how you work with video and we’ll keep you informed as access becomes available.</p></div><EarlyAccessForm /></div></section>
      <section className="cut-section cut-container lab-section-new" id="about" aria-labelledby="lab-title"><div><p className="cut-eyebrow">THE COMPANY</p><h2 id="lab-title">Built by<br />Praha Lab.</h2></div><div><p>Praha Lab is an early-stage AI company building intelligent systems that combine reasoning models with purpose-built tools. Our wider technical work spans agents, voice AI, and efficient inference.</p><dl><div><dt>Founded</dt><dd>2026</dd></div><div><dt>Based in</dt><dd>India</dd></div><div><dt>Field</dt><dd>AI / Machine Learning</dd></div><div><dt>Founder</dt><dd>Pranav Harshan</dd></div></dl><a href="https://www.linkedin.com/in/pranavharshan-s">Meet the founder ↗</a></div></section>
      <section className="research-teaser cut-container" aria-labelledby="research-title"><div><p className="cut-eyebrow">RESEARCH & OPEN SOURCE</p><h2 id="research-title">The work behind<br />the lab.</h2><p>Public models, datasets, and code document what Praha Lab and its founder have built.</p><Link href="/research">Explore public work <span aria-hidden="true">↗</span></Link></div><div className="research-teaser-list">{projects.slice(0, 3).map((project, index) => <a href={project.href} key={project.title}><span>{String(index + 1).padStart(2, "0")}</span><strong>{project.title}</strong><span aria-hidden="true">↗</span></a>)}</div></section>
    </div><SiteFooter />
  </main>;
}
