const bars = [18, 34, 24, 42, 57, 29, 19, 47, 62, 39, 27, 52, 31, 14, 35, 56, 41, 26, 17, 50, 61, 35, 21, 44, 54, 30, 16, 39, 58, 33, 23, 47, 60, 36, 18, 42, 56, 28, 20, 49, 54, 32, 23, 43, 61, 37, 21, 45];

export function ProductVisual({ compact = false }: { compact?: boolean }) {
  return <div className={`editor-concept${compact ? " editor-compact" : ""}`} aria-label="Illustrative concept of the Praha Cut video editing interface">
    <div className="editor-top"><div className="editor-top-brand"><span className="editor-icon">▥</span><strong>praha <em>cut</em></strong><span className="editor-separator">/</span><span>Launch film</span></div><span className="editor-top-state"><span /> Draft 01 · Editing concept</span><span className="editor-top-export">Export ↗</span></div>
    <div className="editor-workspace">
      <aside className="editor-media"><div className="editor-panel-label">Project media <span>03</span></div><div className="editor-media-item is-selected"><span className="media-thumb media-thumb-one"><b>01</b></span><span><strong>founder_take.mov</strong><small>12:43 · 4K</small></span></div><div className="editor-media-item"><span className="media-thumb media-thumb-two"><b>02</b></span><span><strong>benchmark.mov</strong><small>02:16 · 4K</small></span></div><div className="editor-media-item"><span className="media-thumb media-thumb-three"><b>03</b></span><span><strong>interface.mov</strong><small>01:08 · 4K</small></span></div><div className="editor-media-bottom">TRANSCRIPT <span>READY</span></div></aside>
      <div className="editor-stage"><div className="editor-stage-head"><span>Preview</span><span>16:9 <i /> 1080p</span></div><div className="editor-video"><div className="editor-video-grid" /><div className="editor-video-marker">FRAME 04:18:06</div><div className="editor-video-content"><span>THE RESULT</span><strong>Build faster.<br /><i>Keep control.</i></strong><div className="editor-video-terminal"><span>➜ benchmark.run()</span><span>inference latency <b>↓</b></span></div></div><div className="editor-video-caption">This is where the results change the story.</div><div className="editor-video-corner corner-one" /><div className="editor-video-corner corner-two" /><div className="editor-video-corner corner-three" /><div className="editor-video-corner corner-four" /></div><div className="editor-transport"><span>◀◀</span><strong>▶</strong><span>▶▶</span><time>00:04:18:06</time><span>01:00</span></div></div>
      <aside className="editor-agent"><div className="editor-panel-label">Agent <span className="agent-online"><i /> Planning</span></div><div className="editor-message editor-user"><small>YOU</small><p>Make this a 45-second launch video. Open with the benchmark result and remove the long pauses.</p></div><div className="editor-message editor-reply"><small>PRAHA CUT / CLAUDE</small><p>I found the strongest result at 04:18. I&apos;ll build the opening around it and keep the explanation that follows.</p></div><div className="editor-activity"><span>✓ &nbsp; Removed 6 pauses</span><span>✓ &nbsp; Moved result to opening</span><span>✓ &nbsp; Added captions</span><span>✓ &nbsp; Reframed terminal segment</span><span className="editor-activity-current">↗ &nbsp; Rendering draft</span></div><div className="editor-prompt">Describe a revision <span>↗</span></div></aside>
    </div>
    <div className="editor-timeline"><div className="timeline-tools"><strong>Timeline</strong><span>↶ &nbsp; ↷ &nbsp; ✂ &nbsp; ◇</span><span>00:00 &nbsp;&nbsp; 00:15 &nbsp;&nbsp; 00:30 &nbsp;&nbsp; 00:45</span></div><div className="timeline-body"><div className="timeline-track-labels"><span>V1 &nbsp; VIDEO</span><span>A1 &nbsp; AUDIO</span><span>C1 &nbsp; CAPTIONS</span></div><div className="timeline-tracks"><div className="timeline-ruler"><span>00:00</span><span>00:15</span><span>00:30</span><span>00:45</span></div><div className="timeline-video"><span>BENCHMARK RESULT</span><span>FOUNDER</span><span>PRODUCT DEMO</span><span>END FRAME</span></div><div className="timeline-audio" aria-hidden="true">{bars.map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div><div className="timeline-captions"><span>Build faster.</span><span>Keep control.</span><span>See what matters.</span></div><div className="timeline-playhead" /></div></div></div>
    <p className="concept-disclosure">Interface concept · Illustrative workflow, not a captured product session or generated output.</p>
  </div>;
}
